const HOME = "HOME";
const HOTPRODUCT = "HOTPRODUCT";

//category
const CATEGORY = "CATEGORY";
const CATEGORYLISTDETAIL = "CATEGORYLISTDETAIL";
const CATEGORYDETAIL = "CATEGORYDETAIL";

// coupon
const LISTCOUPON = "LISTCOUPON";
const COUPON = "COUPON";
const COUPONDETAIL = "COUPONDETAIL";

export { HOME, COUPON, CATEGORY, HOTPRODUCT, LISTCOUPON, COUPONDETAIL, CATEGORYLISTDETAIL, CATEGORYDETAIL };