const HOME = "HOME";
const COUPON = "COUPON";
const CATEGORY = "CATEGORY";
const HOTPRODUCT = "HOTPRODUCT";
const LISTCOUPON = "LISTCOUPON";

export { HOME, COUPON, CATEGORY, HOTPRODUCT, LISTCOUPON };