const HOME = "HOME";
const CATEGORY = "CATEGORY";
const HOTPRODUCT = "HOTPRODUCT";
// coupon
const LISTCOUPON = "LISTCOUPON";
const COUPON = "COUPON";
const COUPONDETAIL = "COUPONDETAIL";

export { HOME, COUPON, CATEGORY, HOTPRODUCT, LISTCOUPON, COUPONDETAIL };