const HOME = "HOME";
const COUPON = "COUPON";
const EXPERIENCE = "EXPERIENCE";
const HOTPRODUCT = "HOTPRODUCT";
const LISTCOUPON = "LISTCOUPON";

export { HOME, COUPON, EXPERIENCE, HOTPRODUCT, LISTCOUPON};