// type Fetch
export const FETCH_TOPPRODUCT = 'FETCH_TOPPRODUCT';
export const FETCH_OFFERSINFORNATIONS = 'FETCH_OFFERSINFORNATIONS';
export const FETCH_PROMOTION = 'FETCH_PROMOTION';

// type Fetch PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_MOREPRODUCT = 'FETCH_MOREPRODUCT';


// Type Fetch by redux-saga
export const FETCH_OFFERSINFORNATIONS_SUCCEEDED = 'FETCH_OFFERSINFORNATIONS_SUCCEEDED';

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_MORE_SUCCEEDED = 'FETCH_MORE_SUCCEEDED';

export const FETCH_FAILED = 'FETCH_FAILED';

// redux-saga PRODUCT
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED';
export const FETCH_MORE_PRODUCT_SUCCEEDED = 'FETCH_MORE_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED = 'FETCH_FAILED';