// type Fetch
export const FETCH_TOPPRODUCT = 'FETCH_TOPPRODUCT';
export const FETCH_OFFERSINFORNATIONS = 'FETCH_OFFERSINFORNATIONS';
export const FETCH_PROMOTION = 'FETCH_PROMOTION';

// type Fetch PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_MOREPRODUCT = 'FETCH_MOREPRODUCT';

// type Fetch COUPON SHOP
export const FETCH_COUPON_SHOP = 'FETCH_COUPON_SHOP';

// Type Fetch by redux-saga
export const FETCH_OFFERSINFORNATIONS_SUCCEEDED = 'FETCH_OFFERSINFORNATIONS_SUCCEEDED';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_MORE_SUCCEEDED = 'FETCH_MORE_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';

// redux-saga PRODUCT
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED';
export const FETCH_MORE_PRODUCT_SUCCEEDED = 'FETCH_MORE_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED = 'FETCH_FAILED';

// redux-saga COUPON
export const FETCH_COUPON_SHOP_SUCCEEDED = 'FETCH_COUPON_SHOP_SUCCEEDED';
export const FETCH_COUPON_SHOP_FAILED = 'FETCH_COUPON_SHOP_FAILED';

// type check connent internet
export const FETCH_CONNECTIVITY = 'FETCH_CONNECTIVITY';
export const FETCH_SUCCEEDED_CONNECTIVITY = 'FETCH_SUCCEEDED_CONNECTIVITY';