// type Fetch
export const FETCH_TOPPRODUCT = 'FETCH_TOPPRODUCT';
export const FETCH_OFFERSINFORNATIONS = 'FETCH_OFFERSINFORNATIONS';
export const FETCH_PROMOTION = 'FETCH_PROMOTION';


// Type Fetch by redux-saga
export const FETCH_OFFERSINFORNATIONS_SUCCEEDED = 'FETCH_OFFERSINFORNATIONS_SUCCEEDED';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_MORE_SUCCEEDED = 'FETCH_MORE_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';